FROM python:3.13-slim
WORKDIR /app
COPY ../src/streamlit/dashboard.py .
COPY ../resources/data_preprocessing/label_encoders.pkl ./label_encoders.pkl
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.enableCORS=false"]
